//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace individual_project_lombard.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProduct
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
    }
}
