//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace individual_project_lombard.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Money
    {
        public int ID { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Loss { get; set; }
    }
}
